# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: add bot credentials
#      https://stackoverflow.com/questions/57720484/how-to-import-private-data-with-github-actions
      run: |
        echo 'bot.token=${{ secrets.BOT_TOKEN }}' >> ./src/main/resources/application.properties
        echo 'bot.name=${{ secrets.BOT_NAME }}' >> ./src/main/resources/application.properties
    - name: Build with Maven
      run: mvn -B package --file pom.xml
